-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 21:51:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbvivienda
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbbusquedavivienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbbusquedavivienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbbusquedavivienda` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `dbbusquedavivienda` ;

-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `fechaUltimoInicioSesion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idAdministrador`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(150) NOT NULL,
  `numExt` VARCHAR(20) NOT NULL,
  `numInt` VARCHAR(20) NULL DEFAULT NULL,
  `colonia` VARCHAR(100) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `codigoPostal` CHAR(5) NOT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NOT NULL,
  `apellidoMaterno` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `curp` CHAR(18) NULL DEFAULT NULL,
  `username` VARCHAR(60) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `fechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `codigoConfirmacion` VARCHAR(100) NULL DEFAULT NULL,
  `cuentaVerificada` TINYINT(1) NOT NULL DEFAULT '0',
  `fechaConfirmacion` DATETIME NULL DEFAULT NULL,
  `fechaUltimoInicioSesion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `curp` (`curp` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`arrendador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`arrendador` (
  `idArrendador` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idDireccion` INT NOT NULL,
  PRIMARY KEY (`idArrendador`),
  INDEX `fk_arrendador_usuario` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_arrendador_direccion` (`idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_arrendador_direccion`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `dbbusquedavivienda`.`direccion` (`idDireccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_arrendador_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbbusquedavivienda`.`usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`propiedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`propiedad` (
  `idPropiedad` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `tipo` ENUM('cuarto', 'departamento', 'casa', 'estudio', 'otro') NOT NULL,
  `numLugares` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `precio` DECIMAL(10,2) NOT NULL,
  `idDireccion` INT NOT NULL,
  `estatus` ENUM('disponible', 'ocupada', 'inactiva') NOT NULL DEFAULT 'disponible',
  `fechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `codigo` VARCHAR(50) NULL DEFAULT NULL,
  `idArrendador` INT NOT NULL,
  PRIMARY KEY (`idPropiedad`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  INDEX `fk_propiedad_direccion` (`idDireccion` ASC) VISIBLE,
  INDEX `fk_propiedad_arrendador` (`idArrendador` ASC) VISIBLE,
  CONSTRAINT `fk_propiedad_arrendador`
    FOREIGN KEY (`idArrendador`)
    REFERENCES `dbbusquedavivienda`.`arrendador` (`idArrendador`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_propiedad_direccion`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `dbbusquedavivienda`.`direccion` (`idDireccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`arrendamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`arrendamiento` (
  `idArrendamiento` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  `renta` DECIMAL(10,2) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `idPropiedad` INT NOT NULL,
  PRIMARY KEY (`idArrendamiento`),
  INDEX `fk_arrendamiento_propiedad` (`idPropiedad` ASC) VISIBLE,
  CONSTRAINT `fk_arrendamiento_propiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `dbbusquedavivienda`.`propiedad` (`idPropiedad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`arrendatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`arrendatario` (
  `idArrendatario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `boleta` VARCHAR(20) NULL DEFAULT NULL,
  `unidadAcademica` VARCHAR(150) NULL DEFAULT NULL,
  `fechaActualizacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idArrendatario`),
  INDEX `fk_arrendatario_usuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_arrendatario_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbbusquedavivienda`.`usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`arrendatario_arrendamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`arrendatario_arrendamiento` (
  `idArrendatario` INT NOT NULL,
  `idArrendamiento` INT NOT NULL,
  `validadoEstudiante` TINYINT(1) NOT NULL DEFAULT '0',
  `validadoArrendador` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idArrendatario`, `idArrendamiento`),
  INDEX `fk_aa_arrendamiento` (`idArrendamiento` ASC) VISIBLE,
  CONSTRAINT `fk_aa_arrendamiento`
    FOREIGN KEY (`idArrendamiento`)
    REFERENCES `dbbusquedavivienda`.`arrendamiento` (`idArrendamiento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aa_arrendatario`
    FOREIGN KEY (`idArrendatario`)
    REFERENCES `dbbusquedavivienda`.`arrendatario` (`idArrendatario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `categoria` ENUM('basico', 'entretenimiento', 'adicional', 'seguridad') NOT NULL,
  PRIMARY KEY (`idServicio`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`propiedad_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`propiedad_servicio` (
  `idPropiedad` INT NOT NULL,
  `idServicio` INT NOT NULL,
  `usoExclusivo` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idPropiedad`, `idServicio`),
  INDEX `fk_ps_servicio` (`idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_ps_propiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `dbbusquedavivienda`.`propiedad` (`idPropiedad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ps_servicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `dbbusquedavivienda`.`servicio` (`idServicio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbbusquedavivienda`.`resena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbusquedavivienda`.`resena` (
  `idResena` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `duracionRenta` TINYINT UNSIGNED NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `calServiciosBasicos` TINYINT UNSIGNED NULL DEFAULT NULL,
  `calServiciosComEnt` TINYINT UNSIGNED NULL DEFAULT NULL,
  `calServiciosAdicio` TINYINT UNSIGNED NULL DEFAULT NULL,
  `calGeneral` TINYINT UNSIGNED NOT NULL,
  `idArrendatario` INT NOT NULL,
  `idPropiedad` INT NOT NULL,
  PRIMARY KEY (`idResena`),
  INDEX `fk_resena_arrendatario` (`idArrendatario` ASC) VISIBLE,
  INDEX `fk_resena_propiedad` (`idPropiedad` ASC) VISIBLE,
  CONSTRAINT `fk_resena_arrendatario`
    FOREIGN KEY (`idArrendatario`)
    REFERENCES `dbbusquedavivienda`.`arrendatario` (`idArrendatario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resena_propiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `dbbusquedavivienda`.`propiedad` (`idPropiedad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
